FROM node:20-alpine

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

# Utiliser un serveur nginx pour servir le build
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
